### ISSUE TITLE
Add Social implications of Agroecology with Extension

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/introducing-agroecology#1]
- the trap of Extension for industry
- campecina a compacina
- pedagogy of the opressed

**Comment by Danielcalza** [comment]
Fuqua, Winn, Packwood & Hollings, 1983. The Federal Role in Fostering University.

Campesino a Campesino.
https://viacampesina.org/en/ 

Paulo Freire,1970. Pedagogy of the Oppressed.

**Comment by brymz** [comment]
You can close after you add this reference.

Rosset and Altieri. 2017. Agroecology: Science and Politics

**Comment by Danielcalza** [comment]
Okay, the references have been added and a new pull request created.
