### ISSUE TITLE
Industry-University Partnerships Reference

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/introducing-agroecology#21]
Please, add this link to the list of references related to social justice and ethics.

https://www.cambridge.org/core/journals/renewable-agriculture-and-food-systems/article/agrifood-firms-universities-and-corporate-social-responsibility-whats-in-the-public-interest/79CE273EF466BD9C6B4D4D5345420D39

**Comment by Danielcalza** [comment]
Added via pull request #23
