### ISSUE TITLE
Add Agroecosystem Diagram to `Agroecosystem Concept` presentation

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/introducing-agroecology#22]
Upload `.png` to `materials/`. Incorporate into `materials/goals-principles.md`

**Comment by Danielcalza** [comment]
Addressed in #25

**Comment by brymz** [comment]
Next steps... [ to be completed by July 1 ]

- [x] remove agroecosystem image from `materials/goals-principles.md` (_sorry, changed my mind_)
- [x] build agroecosystem progression in `materials/agroecosystems-concept.md`
   - [x] 1st image: whole agroecosystem diagram without red/blue highlights
   - [x] following images: diagram components as per list currently on page (i.e., crop plant)
- [x] last image: whole agroecosystem diagram with red/blue highlights
- [x] remove existing agroecosystem image on `materials/agroecosystems-concept.md`

Image needs...
- [x] invertebrate community composite with no background
- [x] vertebrate community composite with no background
- [x] whole agroecosystem without highlights

**Comment by brymz** [comment]
I am going to merge #27 and close #28. 

@Danielcalza...
- Review [the page](https://trec-agroecology.github.io/introducing-agroecology/materials/agroecosystems-concept/) and add any comments/revisions in this issue 
OR
- Close the issue.

**Comment by Danielcalza** [comment]
The page looks excellent! 

My only comment is that the `[full-size image]` boxes do not lead to the image, all of them have `404: Page not found` message.

**Comment by brymz** [comment]
Good spot! I think it's an easy fix.

**Comment by brymz** [comment]
Fixed the broken link. 

Last thing for consistency, please, @Danielcalza. Can you make an image for the "plant community" that does not include the crop, does not include the highlights, but includes the environment background? It should match the images you did for the invertebrate and vertebrate communities. You can put it in the network folder and let me know you got it done, here.

**Comment by Danielcalza** [comment]
Okay great, and done. 
Pathway: Agronomy > Gallery > Agroecosystem-diagram-photos

**Comment by brymz** [comment]
Looks good.
