### ISSUE TITLE
Fix broken Materials page

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/introducing-agroecology#24]
Looks like there was a failed merge conflict resolution on https://trec-agroecology.github.io/introducing-agroecology/materials/

Where else might that have happened?

**Comment by Danielcalza** [comment]
I see the conflict but not sure how it happened, I'll look back over the last commits to see if I find anything.

**Comment by Danielcalza** [comment]
I am not sure if there are any other bugs, but I did go through most of the pages and all seems well.

**Comment by brymz** [comment]
I see that you removed a couple of lines that were the notation for a merge conflict (e.g., `<<<HEAD`, `===`). However, there is more to remove that is not related to agroecology: lines 15 to 147 that includes content for 'SQL', 'R' and 'Python' need to be removed.
