### ISSUE TITLE
Deleted IST Objectives

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/introducing-agroecology#30]
I am not sure if they appear another place on the website, but they are not relevant to the home page anymore.

After completing this training, participants were expected to:
- understand the goals and guiding principles of agroecology.
- understand key ecological concepts integrating agriculture, natural resource 
management, and community development.
- be able to describe the components of an agroecosystem and specifically
identify an agroecosystem relevant to his/her work.
- be able to apply the agroecology framework for program development,
specifically in relation to priority work group areas, impact reporting
indicators, and logic models.

**Comment by Danielcalza** [comment]
They were removed from the home page but are still present in the [Agenda](https://trec-agroecology.github.io/introducing-agroecology/agenda.pdf)
