### ISSUE TITLE
SDHS - Farmer's Market activity

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/introducing-agroecology#36]
What grows in Florida?
_
Program Objectives
-	Identify the three main fruits and vegetables that grow in MDC/FL
-	Know where food comes from and where it grows 
-	Address in-field/ Farmers/ diagram where
-      Questions for an agricultural scientist

_
What is the most abundant crop grown throughout FL?

-	What are the three most abundant fruits grown in FL?
o	 Oranges
o	 Grapefruit
o	 Watermelon

-	What are the three most abundant vegetables grown in FL?
o	 Tomatoes
o	 Snap Beans
o	 Cucumbers

_
Questions

1. - What are the most abundant crops grown throughout Miami Dade County?
**A.  Melons, Tomatoes, Snap Beans, Cucumbers
B.   Melons, Eggplant, Peppers, Spinach, Tomatoes
C.   Sweet Corn, Carrots, Potatoes, Snap Beans
D.  Tomatoes,  Okra, Squash, Sweet Corn

2. - What are the most abundant crops grown throughout Florida?
**A.   Oranges, Tomatoes, Melons, Sugarcane
B.   Oranges, Avocadoes, Potatoes, Cucumbers
C.   Sweet Corn, Squash, Peppers, Peppers
D.   Sugarcane, Beans, Carrots, Melons

3. - What would you like to ask an Agricultural Scientist?
- Comment box. 

4. -	What are the most abundant fruits grown throughout Florida?
**A.   Oranges, Grapefruits, Watermelon, Avocados
B.   Oranges, Banana, Strawberries, Avocados
C.   Papaya, Jackfruit, Pineapple, Strawberries
D.   Dragon fruit, Avocado, Passionfruit, Bananas

5. -	What are the most abundant vegetables grown throughout Florida?
**A.   Tomatoes,  Snap Beans, Cucumbers, Melons
B.   Tomatoes,  Okra, Squash, Snap Beans
C.   Eggplant, Peppers, Spinach, Melons
D.   Sweet Corn, Carrots, Potatoes, Okra

6. - Where does food come from?
**A. Seeds, Plants, Animals
B. Seeds, Markets, Stores
C. Plants, Animals, Trucks
D. Farmers, Tractors, Fields

7. - Where does food grow?
-- Fill in the blank with at least three items. 
**Gardens, Forests, Jungles, Water bodies, Farms, Orchards/Groves, Fields, Ranches, Buildings/Indoors
Soil, Water

8. - How does food grow?
-- Fill in the blank with at least three items. 
**Sun, Water, Soil, Farmers, Fertilizer

9. - How does food get to you?
-- Fill in the blank with at least three items. 
**Harvest workers and mechanical tractors, Packers, Trucks, Farmers markets, Grocery stores

10. - What is an ecosystem?
-- Fill in the blank, explain.
**A community of living organisms in conjunction with the nonliving components of their environment, interacting as a system. [Wikipedia]

11. - Is a farm an ecosystem?
-- Fill in the blank, explain.
**Yes, an agricultural ecosystem - The plants, animals, farmer, and you (consumer) along with the water, air, sun, and soil - all working together to produce food and maintain the system - in a healthy system with checks and balances to ensure sustainability.

_

Farmer’s Market – Jed’s fresh produce stand
_
Yes, it grows.
o	Vegetables
-	Corn
-	Watermelon/melons (Cantaloup)
-	Pumpkin/Gourds
-	Squash
-	Carrots
-	Cucumber
-	Eggplant
-	Tomatoes
-	Potatoes/Sweet potatoes
-	Leafy greens/Arugula/Collards/Kale/Mustard/Chard/Lettuces/Spinach
-	Cauliflower

o	Fruits
-	Bananas
-	Oranges 

o	Not pictured
_
o	Blueberries
o	Grapefruits
o	Tangerines
o	Blackberries
o	Strawberries
o	Avocadoes
o	Mangoes
o	Figs
o	Mulberry
o	Pomegranates
o	Other tropical fruits

o	Nuts, Seeds and other

-	Peanuts
-	Pecans
-	Walnuts
-	Macadamia 
-	Cashew 
-	Sesame
-	Sunflower 
-	Pumpkin
-	Hemp
-	Sugarcane

o	Yes it grows but not pictured
_
o	Asian Vegetables
o	Kohlrabi
o	Bell peppers
o	Beans – Bush/pole
o	Snap Bean 
o	Lima Bean
o	Snow Pea 
o	Southern Pea 
o	Specialty Vegetables 
o	Beets 
o	Boniato 
o	Broccoli 
o	Brussels Sprouts 
o	Cabbage 
o	Celery
o	Chives 
o	Herbs
o	Leeks 
o	Okra 
o	Onions
o	Radish 
o	Turnip

_

No, it does not grow. 
o	Vegetables
-	Rhubarb
-	Asparagus 
-	

o	Fruits
-	Apples
-	Cherry
-	Apricot
-	Crabapples
-	Pears
-	Peaches
-	Nectarines
-	Plums
-	Grapes

o	Nuts and Seeds	
-	Chestnuts
-	Hazelnuts
-	Pistachios
-	Almonds
-	Brazil nuts 
-	Pignut hickory
	
_
State Agriculture Overview (2002) https://www.nass.usda.gov/Quick_Stats/Ag_Overview/stateOverview.php?state=FLORIDA 

o	Livestock
-	Cattle, Cows, Beef – 929,000
-	Cattle, Cows, Milk – 111,000
-	Chickens, Broilers – 78,500,000
-	Chickens, Eggs – 11,300,000
-	Horses – 500,000
-	Hogs – 100,000
-	Goats, Meat & Other – 47,000
-	Goats, Milk – 9,000
-	Beehives – 650,000

o	Florida Ag stats. (2016) (https://farmlandinfo.org/statistics/florida-statistics/) 
-	Acres of total land area – 34,320,000 – 36,628,500 
-	Acres in production/operation – 9,700,000 – 8,417,200 
-	Number of farms – 47,590
-	Crop land – 2,527,900
-	Pastureland – 3,062,700
-	Rangeland – 1,359,300
-	Woodland – 1,467,300

-	Number of farmers/producers 34 and younger – 5,038
-	Number of farmers/producers 65 and older – 28,920
-	Number of farmers/producers w/<10 yrs. – 45,352 
-	Market value of all agricultural products sold – $7,357,343,000
-	Average market value of products per operation – $154,599

_

Priority Working Group 3 (PWG-3) - Statewide Education Programs in Citizen Awareness of Food Systems and the Environment
 
Objectives

1. Directly following a program activity,  report increased knowledge of at least two aspects of agriculture and/or its importance to the state of Florida, measured by a survey.
- Production types or systems
- Local farmers/producers and the diversity of farmers/producers/farmworkers

2. Directly following a program activity,  report positive changes in attitudes of least two aspects of agriculture and/or its importance to the state of Florida, measured by a survey.

- View of agriculture as important for food security
- Believe that it's important to conserve and protect agricultural lands

3. Annually, report adopting at least one new practice that supports Florida agriculture, measured by follow-up survey. 

- Encouraging youth to explore/pursue careers in agriculture
_

**Comment by Danielcalza** [comment]
@brymz  Please review the questions and let me know which ones to build out the polls - I am going with Survey Monkey and have one built with questions 1-3.

**Comment by brymz** [comment]
## Farms in Florida

### Program Objectives
- Identify the fruits planted on the most land in FL
- Identify the vegetable planted on the most land in FL
- Farms are critical for food security
- Farming and ag science careers

### Pre Survey
What is the most abundant fruit grown throughout FL?
- [ ] Watermelon
- [x] Orange
- [ ] Mango
- [ ] Strawberry

What is the most abundant vegetable grown throughout FL?
- [x] Tomatoes
- [ ] Snap Beans
- [ ] Cucumbers
- [ ] Corn

Agriculture in Florida is critical for food security?
- Strongly Agree - Strongly Disagree

Do you have a question for an Agricultural Scientist?
- Comment box 

### Post Survey
*Text in brackets is for our reference and should not be included in survey*

What is the most abundant fruit grown throughout FL?
[report increased knowledge in food production]
- [ ] Strawberry
- [ ] Watermelon
- [x] Orange
- [ ] Mango

What is the most abundant vegetable grown throughout FL?
[report increased knowledge in food production]
- [ ] Cucumbers
- [ ] Tomatoes
- [ ] Snap Beans
- [x] Corn

What is the most abundant fruit grown throughout Miami Dade County?
[report increased knowledge in local production]
- [ ] ???
- [ ] ???
- [ ] ???
- [ ] ???

What is the most abundant vegetable grown throughout FL?
[report increased knowledge in local production]
- [ ] ???
- [ ] ???
- [ ] ???
- [ ] ???

Agriculture in Florida is critical for food security.
- Strongly Agree - Strongly Disagree

Agricultural lands in Florida should be conserved and protected.
- Strongly Agree - Strongly Disagree

I can see myself in a career in agriculture.
- Strongly Agree - Strongly Disagree

Do you have any follow up questions for Zack and Daniel?

### Intros
- Zack
- Daniel
- Food/Farm/Farmer

### Florida Ag
- Land in Florida
- Ag land in Florida
- Most land in fruit
- Most land in vegetable

Florida Ag stats. (2016) (https://farmlandinfo.org/statistics/florida-statistics/) 
-	Acres of total land area – 34,320,000 – 36,628,500 
-	Acres in production/operation – 9,700,000 – 8,417,200 
-	Number of farms – 47,590
-	Crop land – 2,527,900
-	Pastureland – 3,062,700
-	Rangeland – 1,359,300
-	Woodland – 1,467,300

State Agriculture Overview (2002) https://www.nass.usda.gov/Quick_Stats/Ag_Overview/stateOverview.php?state=FLORIDA 

### Jed’s fresh produce stand
- Where do you think this farm stand is located across the country?
- Which of these grow in Florida

Yes, it grows.
- Corn
- Watermelon/melons (Cantaloup)
- Pumpkin/Gourds
- Squash
- Carrots
- Cucumber
- Eggplant
- Tomatoes
- Potatoes/Sweet potatoes
- Leafy greens
- Cauliflower
- Bananas
- Oranges
- Cows
- Chickens
- Goats
- Horses
- Hogs
- Bees

No, it does not grow. 
- Rhubarb
- Asparagus 
- Apples
- Cherry
- Apricot
- Pears
- Peaches
- Nectarines
- Plums
- Grapes
- Tree Nuts

**Comment by Danielcalza** [comment]
Notes:

-Florida citrus growers in 2015-2016 produced 81.6 million boxes of oranges and 10.8 million boxes of grapefruit.

-Florida growers harvested vegetables for fresh market, potatoes, sweet potatoes, strawberries, and blueberries from 198,600 acres in 2016. 

-FL – 38,403 acres in Sweet Corn.
-FL – 422,421 acres in Orange. 

-MDC – 6,193 acres in Avocado.
-MDC – 7,555 acres in Snap Bean.
