### ISSUE TITLE
Add notes from IST as issues

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/introducing-agroecology#4]

**Comment by Danielcalza** [comment]
Conservation as Business: USDA conservation easement 
-	Part of the solution
-	Synergies and trade-offs
- Ecology in agriculture – The Dust Bowl 
- Market recovery – Farmer’s Markets
- Justification and Messaging for food systems
- Water!
- USDA Food Desert – Map? [#6]
- Boom for FFL – Florida Friendly Landscapes [#6] 
-	Integrate into water conservation and BMP 

---
 
-	Workload indicators  					- Extension first 
-	Permaculture/ By Agroecology/ Food systems 		- Graphics
-	Master Gardener/ Master Naturalist 			- Homesteading/ 
-	Agroecology @ work/ In transition/ Assessment
-	Young kids (4-H, Agriculture in classroom)

**Comment by Danielcalza** [comment]
Notes added and resources moved to: Introducing Agroecology website.
